#define CATEGORY_CLIENT "CLIENT"
#define CATEGORY_ADMIN "ADMIN"
#define CATEGORY_CARBON "CARBON"
#define CATEGORY_HUMAN "HUMAN"
#define CATEGORY_MISC "MISC"
#define CATEGORY_ROBOT "ROBOT"

#define WEIGHT_HIGHEST 0
// AQ EDIT - BEGIN
#define WEIGHT_ADMIN 10
#define WEIGHT_CLIENT 20
#define WEIGHT_ROBOT 30
#define WEIGHT_MOB 40
#define WEIGHT_LIVING 50
#define WEIGHT_DEAD 60
#define WEIGHT_EMOTE 70
// AQ EDIT - END
#define WEIGHT_LOWEST 999
